# Configurations
title:            AcaciaLinux
longtitle:        AcaciaLinux - Documentation
author:           Max Kofler
email:            kofler.max.dev@gmail.com
description: >
  The AcaciaLinux documentation

version:          1.0
gitbook_version:  3.2.3

# bootstrap: use the remote theme for the site itself
remote_theme: sighingnow/jekyll-gitbook

baseurl: '/concept'

toc:
  enabled: true
  h_min: 1
  h_max: 3

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     /assets/gitbook/images/favicon.ico

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

syntax_highlighter_style: gruvbox

markdown_ext:             markdown,mkdown,mkdn,mkd,md

# Permalinks

# Disqus comments
# disqushandler:            sighingnow

exclude:
  - _drafts

collections:
  pages:
    output: true
    permalink: /:collection/:path/

page_width: 90%

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji
